<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System appex created in: 2022-08-17 01:36:21
 */
class tb_uf extends TRecord
{
    const TABLENAME = 'tb_uf';
    const PRIMARYKEY= 'cod_uf';
    const IDPOLICY  = 'serial'; //{max, serial}

    public function __construct($id = NULL, $callObjectLoad = TRUE)
    {
        parent::__construct($id, $callObjectLoad);
        parent::addAttribute('sig_uf');
        parent::addAttribute('nom_uf');
        parent::addAttribute('cod_regiao');
    }

}
?>